// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTDn4AZ2yqXTJvVsDPnA2uNaFRU1iUHQg',
    appId: '1:580452483330:web:007be748bc12fd0b71c21b',
    messagingSenderId: '580452483330',
    projectId: 'catalogo-peliculas-fda19',
    authDomain: 'catalogo-peliculas-fda19.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-fda19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKASUzwRuvz3Msq0jGS2HfcxyyyyoZfGs',
    appId: '1:580452483330:android:95d10606ac3167da71c21b',
    messagingSenderId: '580452483330',
    projectId: 'catalogo-peliculas-fda19',
    storageBucket: 'catalogo-peliculas-fda19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvq0_47UMuihsXDCCxykdhHeIG-QTH9gI',
    appId: '1:580452483330:ios:319bec611fb56f2471c21b',
    messagingSenderId: '580452483330',
    projectId: 'catalogo-peliculas-fda19',
    storageBucket: 'catalogo-peliculas-fda19.firebasestorage.app',
    iosBundleId: 'com.example.catalogoPeliculas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvq0_47UMuihsXDCCxykdhHeIG-QTH9gI',
    appId: '1:580452483330:ios:319bec611fb56f2471c21b',
    messagingSenderId: '580452483330',
    projectId: 'catalogo-peliculas-fda19',
    storageBucket: 'catalogo-peliculas-fda19.firebasestorage.app',
    iosBundleId: 'com.example.catalogoPeliculas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTDn4AZ2yqXTJvVsDPnA2uNaFRU1iUHQg',
    appId: '1:580452483330:web:5fd3bda17e2abecd71c21b',
    messagingSenderId: '580452483330',
    projectId: 'catalogo-peliculas-fda19',
    authDomain: 'catalogo-peliculas-fda19.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-fda19.firebasestorage.app',
  );
}
